data = [
    ("Ich bin so froh!", "glücklich"),
    ("Das ist enttäuschend.", "traurig"),
    ("Ich fühle mich betrogen.", "wütend"),
    ("Ich bin zufrieden mit dem Ergebnis.", "neutral"),
    ("Ich finde es toll!", "glücklich"),
    ("Das macht mich wütend!", "wütend"),
    ("Das ist wirklich traurig.", "traurig"),
    ("Ich bin entspannt.", "neutral"),
    ("Ich freue mich auf das Wochenende.", "glücklich"),
    ("Das ist frustrierend.", "wütend"),
    ("Ich bin enttäuscht von dir.", "traurig"),
    ("Ich fühle mich gut.", "neutral"),
    ("Das war großartig!", "glücklich"),
    ("Ich bin sauer auf die Situation.", "wütend"),
    ("Es macht mich nachdenklich.", "neutral"),
    ("Ich bin glücklich, hier zu sein.", "glücklich"),
    ("Das ist eine schlechte Nachricht.", "traurig"),
    ("Ich kann nicht glauben, dass das passiert ist!", "wütend"),
    ("Ich fühle mich leer.", "neutral"),
    ("Ich genieße die Zeit mit meinen Freunden.", "glücklich"),
    ("Das hat mir das Herz gebrochen.", "traurig"),
    ("Ich kann nicht mehr warten!", "wütend"),
    ("Es ist ein schöner Tag.", "neutral"),
    ("Ich bin stolz auf dich!", "glücklich"),
    ("Ich fühle mich verletzt.", "traurig"),
    ("Ich bin frustriert über die Situation.", "wütend"),
    ("Ich bin ruhig.", "neutral"),
    ("Ich bin begeistert von diesem Projekt.", "glücklich"),
    ("Das hat mich sehr traurig gemacht.", "traurig"),
    ("Ich mag das nicht!", "wütend"),
    ("Ich fühle mich sicher.", "neutral"),
    ("Ich bin glücklich mit meiner Entscheidung.", "glücklich"),
    ("Das ist unglücklich.", "traurig"),
    ("Ich kann nicht glauben, dass du das gesagt hast!", "wütend"),
    ("Ich bin optimistisch.", "neutral"),
    ("Ich habe viel Spaß!", "glücklich"),
    ("Es macht mich traurig, dich zu sehen.", "traurig"),
    ("Ich bin verärgert über die Lüge.", "wütend"),
    ("Ich bin gelassen.", "neutral"),
    ("Ich liebe dieses Lied!", "glücklich"),
    ("Das ist sehr bedauerlich.", "traurig"),
    ("Ich bin enttäuscht über dein Verhalten.", "wütend"),
    ("Ich fühle mich wohl.", "neutral"),
    ("Ich bin so aufgeregt!", "glücklich"),
    ("Das ist nicht fair.", "wütend"),
    ("Ich vermisse die guten alten Zeiten.", "traurig"),
    ("Ich fühle mich leicht.", "neutral"),
    ("Ich bin glücklich, dass ich dir helfen konnte.", "glücklich"),
    ("Das ist einfach traurig.", "traurig"),
    ("Ich kann nicht glauben, dass du das getan hast.", "wütend"),
    ("Ich bin dankbar für alles.", "neutral"),
    ("Ich freue mich auf die Zukunft.", "glücklich"),
    ("Das hat mich enttäuscht.", "traurig"),
    ("Ich bin wütend auf die Ungerechtigkeit.", "wütend"),
    ("Ich fühle mich geliebt.", "neutral"),
    ("Ich bin überglücklich!", "glücklich"),
    ("Das macht mich nachdenklich.", "traurig"),
    ("Ich bin richtig sauer!", "wütend"),
    ("Ich fühle mich ausgeglichen.", "neutral"),
    ("Ich bin so stolz auf meine Leistungen!", "glücklich"),
    ("Das ist einfach nur traurig.", "traurig"),
    ("Ich kann nicht glauben, dass das passiert ist.", "wütend"),
    ("Ich bin ganz ruhig.", "neutral"),
    ("Ich freue mich, dich zu sehen!", "glücklich"),
    ("Das macht mich unglücklich.", "traurig"),
    ("Ich kann nicht fassen, dass du das gesagt hast.", "wütend"),
    ("Ich fühle mich gut, so wie ich bin.", "neutral"),
    ("Ich bin begeistert von diesem Buch!", "glücklich"),
    ("Das ist sehr betrüblich.", "traurig"),
    ("Ich bin wütend über die Unfairness.", "wütend"),
    ("Ich bin optimistisch für die Zukunft.", "neutral"),
    ("Ich bin froh, dass ich helfen konnte.", "glücklich"),
    ("Das ist einfach schrecklich.", "traurig"),
    ("Ich bin sauer auf die Verspätung.", "wütend"),
    ("Ich fühle mich wohl in meiner Haut.", "neutral"),
    ("Ich bin glücklich, wenn ich die Sonne sehe.", "glücklich"),
    ("Das tut mir leid zu hören.", "traurig"),
    ("Ich bin enttäuscht von den Ergebnissen.", "wütend"),
    ("Ich bin entspannt und glücklich.", "neutral"),
    ("Ich finde das echt toll!", "glücklich"),
    ("Es macht mich traurig, wenn du weinst.", "traurig"),
    ("Ich kann nicht glauben, dass das passiert ist!", "wütend"),
    ("Ich fühle mich voller Energie.", "neutral"),
    ("Ich bin überglücklich mit meinem Leben!", "glücklich"),
    ("Das macht mich traurig und nachdenklich.", "traurig"),
    ("Ich bin frustriert über die fehlende Kommunikation.", "wütend"),
    ("Ich bin zufrieden mit dem, was ich habe.", "neutral"),
    ("Ich bin so froh, dass wir Freunde sind!", "glücklich"),
    ("Das ist echt schade.", "traurig"),
    ("Ich bin wütend, dass du das getan hast.", "wütend"),
    ("Ich fühle mich gelassen und ruhig.", "neutral"),
    ("Ich bin glücklich, dass wir das zusammen geschafft haben.", "glücklich"),
    ("Das macht mich wirklich traurig.", "traurig"),
    ("Ich kann nicht glauben, dass ich verloren habe.", "wütend"),
    ("Ich bin froh, dass du hier bist.", "neutral"),
    ("Ich finde das großartig!", "glücklich"),
    ("Das macht mich sehr nachdenklich.", "traurig"),
    ("Ich bin wütend auf die schlechten Nachrichten.", "wütend"),
    ("Ich fühle mich sicher und geborgen.", "neutral"),
    ("Ich bin glücklich, wenn ich tanze.", "glücklich"),
    ("Das ist wirklich bedauerlich.", "traurig"),
    ("Ich bin enttäuscht über dein Verhalten.", "wütend"),
    ("Ich fühle mich frei.", "neutral"),
    ("Ich bin so froh über meine Entscheidung!", "glücklich"),
    ("Das macht mich sehr traurig.", "traurig"),
    ("Ich bin frustriert über die Situation.", "wütend"),
    ("Ich fühle mich glücklich in diesem Moment.", "neutral"),
    ("Ich bin glücklich, wenn ich lache.", "glücklich"),
    ("Das ist wirklich deprimierend.", "traurig"),
    ("Ich bin wütend über die Ungerechtigkeit.", "wütend"),
    ("Ich fühle mich neutral über die Situation.", "neutral"),
    ("Ich freue mich auf die Ferien!", "glücklich"),
    ("Das macht mich sehr unglücklich.", "traurig"),
    ("Ich kann nicht glauben, dass ich so behandelt werde.", "wütend"),
    ("Ich fühle mich ruhig und gelassen.", "neutral"),
    ("Ich bin so froh, dass ich gewonnen habe!", "glücklich"),
    ("Das ist traurig, dass du das denkst.", "traurig"),
    ("Ich bin enttäuscht von meiner Leistung.", "wütend"),
    ("Ich fühle mich stark und sicher.", "neutral"),
    ("Ich bin glücklich, dass du hier bist!", "glücklich"),
    ("Es macht mich traurig, dass wir uns nicht sehen können.", "traurig"),
    ("Ich kann nicht glauben, dass du mich angelogen hast!", "wütend"),
    ("Ich bin einfach zufrieden.", "neutral"),
    ("Ich bin so froh, dass ich Zeit für mich habe.", "glücklich"),
    ("Das tut mir wirklich leid.", "traurig"),
    ("Ich bin wütend über die Versprechen, die nicht gehalten wurden.", "wütend"),
    ("Ich fühle mich entspannt und wohl.", "neutral"),
    ("Ich finde es großartig, neue Dinge zu lernen.", "glücklich"),
    ("Das ist sehr betrüblich für mich.", "traurig"),
    ("Ich bin frustriert über die ständigen Probleme.", "wütend"),
    ("Ich bin zufrieden mit meinem Fortschritt.", "neutral"),
    ("Ich bin überglücklich mit der Unterstützung meiner Freunde!", "glücklich"),
    ("Das macht mich sehr nachdenklich.", "traurig"),
    ("Ich kann nicht glauben, dass das passiert ist!", "wütend"),
    ("Ich fühle mich wohl in meiner Umgebung.", "neutral"),
    ("Ich bin so glücklich über die Überraschung!", "glücklich"),
    ("Das ist einfach nur schade.", "traurig"),
    ("Ich bin wütend über die ständigen Ausreden.", "wütend"),
    ("Ich bin gelassen in dieser Situation.", "neutral"),
    ("Ich bin glücklich, wenn ich Zeit mit meiner Familie verbringe.", "glücklich"),
    ("Das ist wirklich schockierend.", "traurig"),
    ("Ich kann nicht glauben, dass du das getan hast!", "wütend"),
    ("Ich fühle mich wohl in meiner Haut.", "neutral"),
    ("Ich bin glücklich über die neuen Möglichkeiten.", "glücklich"),
    ("Das ist enttäuschend zu hören.", "traurig"),
    ("Ich bin wütend über die schlechten Nachrichten.", "wütend"),
    ("Ich fühle mich ausgeglichen und ruhig.", "neutral"),
    ("Ich bin so froh über meine Freunde!", "glücklich"),
    ("Das ist traurig, dass du leidest.", "traurig"),
    ("Ich kann nicht glauben, dass sie so reagiert haben.", "wütend"),
    ("Ich bin zufrieden mit dem, was ich erreicht habe.", "neutral"),
    ("Ich bin glücklich, dass ich reisen kann.", "glücklich"),
    ("Das macht mich traurig, dass du dich so fühlst.", "traurig"),
    ("Ich bin frustriert über die ständigen Schwierigkeiten.", "wütend"),
    ("Ich fühle mich geliebt und geschätzt.", "neutral"),
    ("Ich bin begeistert von dieser Idee!", "glücklich"),
    ("Das macht mich traurig, dass wir uns trennen müssen.", "traurig"),
    ("Ich bin wütend, weil du gelogen hast.", "wütend"),
    ("Ich fühle mich neutral über die aktuelle Situation.", "neutral"),
    ("Ich freue mich auf das Konzert!", "glücklich"),
    ("Das hat mich wirklich enttäuscht.", "traurig"),
    ("Ich bin wütend über die Verspätung der Lieferung.", "wütend"),
    ("Ich bin zufrieden mit meiner Arbeit.", "neutral"),
    ("Ich bin so froh, dass ich dich getroffen habe!", "glücklich"),
    ("Es macht mich traurig, dass du weinst.", "traurig"),
    ("Ich kann nicht glauben, dass du das gesagt hast!", "wütend"),
    ("Ich fühle mich wohl und geborgen.", "neutral"),
    ("Ich bin glücklich, wenn ich draußen bin.", "glücklich"),
    ("Das ist bedauerlich, dass du nicht kommen kannst.", "traurig"),
    ("Ich bin frustriert über die ständigen Probleme.", "wütend"),
    ("Ich fühle mich entspannt und glücklich.", "neutral"),
    ("Ich bin so stolz auf unser Team!", "glücklich"),
    ("Das macht mich nachdenklich über die Zukunft.", "traurig"),
    ("Ich bin wütend, dass du meine Gefühle nicht respektierst.", "wütend"),
    ("Ich fühle mich stark und positiv.", "neutral"),
    ("Ich finde es toll, neue Freunde zu gewinnen.", "glücklich"),
    ("Das tut mir leid zu hören, es klingt hart.", "traurig"),
    ("Ich bin wütend, dass du mir nicht zuhörst.", "wütend"),
    ("Ich fühle mich zufrieden mit dem, was ich habe.", "neutral"),
    ("Ich bin glücklich, wenn ich Zeit in der Natur verbringe.", "glücklich"),
    ("Das ist traurig, dass du dich so fühlst.", "traurig"),
    ("Ich kann nicht fassen, dass du so reagierst!", "wütend"),
    ("Ich bin gelassen und ruhig geblieben.", "neutral"),
    ("Ich bin glücklich über meine Fortschritte.", "glücklich"),
    ("Das macht mich traurig, dass du so denkst.", "traurig"),
    ("Ich bin wütend über die Unordnung.", "wütend"),
    ("Ich fühle mich frei und unbeschwert.", "neutral"),
    ("Ich bin so froh, dass ich meine Ziele erreicht habe!", "glücklich"),
    ("Das ist enttäuschend, dass du das nicht verstehst.", "traurig"),
    ("Ich kann nicht glauben, dass sie das getan haben!", "wütend"),
    ("Ich fühle mich wohl in dieser Gemeinschaft.", "neutral"),
    ("Ich bin begeistert von der neuen Herausforderung!", "glücklich"),
    ("Das macht mich sehr traurig.", "traurig"),
    ("Ich bin wütend, dass du mich nicht unterstützt.", "wütend"),
    ("Ich fühle mich sicher und geborgen.", "neutral"),
    ("Ich bin glücklich, wenn ich gute Musik höre.", "glücklich"),
    ("Das ist schade, dass wir nicht mehr Zeit haben.", "traurig"),
    ("Ich bin frustriert über die ständigen Rückschläge.", "wütend"),
    ("Ich fühle mich ausgeglichen und zufrieden.", "neutral"),
    ("Ich bin so glücklich, dass du hier bist!", "glücklich"),
    ("Das tut mir leid, dass du leidest.", "traurig"),
    ("Ich kann nicht glauben, dass du mich so behandelst!", "wütend"),
    ("Ich fühle mich gut und positiv.", "neutral"),
    ("Ich bin überglücklich, dass ich bestanden habe!", "glücklich"),
    ("Das macht mich traurig, dass du mich nicht anrufst.", "traurig"),
    ("Ich bin wütend, weil das nicht fair ist.", "wütend"),
    ("Ich fühle mich neutral über die Meinungen anderer.", "neutral"),
    ("Ich freue mich, mit dir zu reisen!", "glücklich"),
    ("Es tut mir leid zu hören, dass du krank bist.", "traurig"),
    ("Ich kann nicht glauben, dass ich die Prüfung nicht bestanden habe!", "wütend"),
    ("Ich bin zufrieden mit meinem Leben.", "neutral"),
    ("Ich bin so froh, dass wir das zusammen machen!", "glücklich"),
    ("Das macht mich traurig, dass wir nicht mehr Zeit haben.", "traurig"),
    ("Ich bin wütend, dass du mich nicht verstehst.", "wütend"),
    ("Ich fühle mich ruhig, wenn ich lese.", "neutral"),
    ("Ich bin glücklich, wenn ich die Natur sehe.", "glücklich"),
    ("Das ist traurig, dass du das nicht schätzt.", "traurig"),
    ("Ich bin frustriert über die ständigen Unterbrechungen.", "wütend"),
    ("Ich fühle mich entspannt, wenn ich meditiere.", "neutral"),
    ("Ich bin so stolz auf meine Familie!", "glücklich"),
    ("Das macht mich nachdenklich, was du gesagt hast.", "traurig"),
    ("Ich kann nicht glauben, dass du das gemacht hast!", "wütend"),
    ("Ich fühle mich sicher in meiner Umgebung.", "neutral"),
    ("Ich bin glücklich, dass ich neue Freunde gefunden habe.", "glücklich"),
    ("Das ist schade, dass du nicht teilnehmen kannst.", "traurig"),
    ("Ich bin wütend über die Ungerechtigkeit in der Welt.", "wütend"),
    ("Ich fühle mich geliebt und geschätzt.", "neutral"),
    ("Ich finde es toll, neue Orte zu entdecken.", "glücklich"),
    ("Das macht mich traurig, dass du so oft allein bist.", "traurig"),
    ("Ich kann nicht fassen, dass ich das vergessen habe!", "wütend"),
    ("Ich bin zufrieden mit meinem Fortschritt in der Schule.", "neutral"),
    ("Ich bin so froh über die Unterstützung meiner Freunde!", "glücklich"),
    ("Das ist enttäuschend, dass du das nicht tun willst.", "traurig"),
    ("Ich bin wütend über die Lügen.", "wütend"),
    ("Ich fühle mich gut, wenn ich kreativ bin.", "neutral"),
    ("Ich bin glücklich, wenn ich gute Nachrichten höre.", "glücklich"),
    ("Das macht mich traurig, dass du leidest.", "traurig"),
    ("Ich bin frustriert über die vielen Aufgaben.", "wütend"),
    ("Ich fühle mich wohl in dieser Stadt.", "neutral"),
    ("Ich bin begeistert von der neuen Herausforderung!", "glücklich"),
    ("Das tut mir leid, dass du so fühlst.", "traurig"),
    ("Ich kann nicht glauben, dass du das für mich getan hast!", "wütend"),
    ("Ich fühle mich ruhig, wenn ich am Meer bin.", "neutral"),
    ("Ich bin so froh, dass wir einen Plan haben!", "glücklich"),
    ("Das ist traurig, dass du nicht verstanden wirst.", "traurig"),
    ("Ich bin wütend, weil meine Erwartungen nicht erfüllt wurden.", "wütend"),
    ("Ich fühle mich positiv und motiviert.", "neutral"),
    ("Ich bin glücklich, dass ich die Gelegenheit habe, zu lernen.", "glücklich"),
    ("Das macht mich traurig, dass wir uns nicht mehr sehen können.", "traurig"),
    ("Ich kann nicht fassen, dass ich verloren habe!", "wütend"),
    ("Ich fühle mich wohl und glücklich hier.", "neutral"),
    ("Ich bin glücklich, dass der Sommer kommt!", "glücklich"),
    ("Das macht mich traurig, dass du traurig bist.", "traurig"),
    ("Ich bin wütend, weil die Dinge nicht laufen wie geplant.", "wütend"),
    ("Ich fühle mich neutral über die Politik.", "neutral"),
    ("Ich freue mich, bald Urlaub zu machen!", "glücklich"),
    ("Es tut mir leid, dass du so viele Probleme hast.", "traurig"),
    ("Ich kann nicht glauben, dass du das getan hast!", "wütend"),
    ("Ich bin zufrieden mit meinem Leben und meinen Entscheidungen.", "neutral"),
    ("Ich bin so froh, dass ich dich wiedersehen kann!", "glücklich"),
    ("Das macht mich traurig, dass wir nicht in Kontakt sind.", "traurig"),
    ("Ich bin wütend, weil ich unfair behandelt werde.", "wütend"),
    ("Ich fühle mich ruhig, wenn ich spazieren gehe.", "neutral"),
    ("Ich bin glücklich über die positive Rückmeldung.", "glücklich"),
    ("Das ist traurig, dass du deine Träume aufgegeben hast.", "traurig"),
    ("Ich bin frustriert über die ständigen Ablenkungen.", "wütend"),
    ("Ich fühle mich sicher in meiner Familie.", "neutral"),
    ("Ich finde es großartig, neue Fähigkeiten zu erlernen.", "glücklich"),
    ("Das macht mich traurig, dass wir uns nicht sehen können.", "traurig"),
    ("Ich bin wütend über die Lügen und Täuschungen.", "wütend"),
    ("Ich fühle mich wohl in meiner Haut.", "neutral"),
    ("Ich bin so froh, dass ich an diesem Projekt arbeite!", "glücklich"),
    ("Das tut mir leid, dass du so fühlst.", "traurig"),
    ("Ich kann nicht glauben, dass ich so etwas erleben muss!", "wütend"),
    ("Ich fühle mich entspannt, wenn ich im Garten arbeite.", "neutral"),
    ("Ich bin glücklich, wenn ich meine Lieblingsmusik höre.", "glücklich"),
    ("Das ist traurig, dass du so oft alleine bist.", "traurig"),
    ("Ich bin wütend, weil ich nicht ernst genommen werde.", "wütend"),
    ("Ich fühle mich zufrieden mit dem, was ich erreicht habe.", "neutral"),
    ("Ich bin begeistert von der Idee, etwas Neues auszuprobieren!", "glücklich"),
    ("Das macht mich traurig, dass du dich zurückziehst.", "traurig"),
    ("Ich bin frustriert über die ständigen Probleme im Team.", "wütend"),
    ("Ich fühle mich wohl und geliebt.", "neutral"),
    ("Ich bin so froh, dass wir gemeinsam lachen können!", "glücklich"),
    ("Das tut mir leid, dass du leidest.", "traurig"),
    ("Ich kann nicht glauben, dass ich versagt habe!", "wütend"),
    ("Ich fühle mich gut, wenn ich Sport treibe.", "neutral"),
    ("Ich bin glücklich, dass ich neue Freunde gefunden habe.", "glücklich"),
    ("Das ist wirklich bedauerlich.", "traurig"),
    ("Ich bin wütend, weil ich meine Zeit verschwende.", "wütend"),
    ("Ich fühle mich stabil und sicher.", "neutral"),
    ("Ich bin so glücklich über die Fortschritte, die ich gemacht habe!", "glücklich"),
    ("Das macht mich traurig, dass du keine Unterstützung hast.", "traurig"),
    ("Ich bin enttäuscht von deinem Verhalten.", "wütend"),
    ("Ich fühle mich positiv und optimistisch.", "neutral"),
    ("Ich bin glücklich, wenn ich im Urlaub bin.", "glücklich"),
    ("Das tut mir leid, dass du so denkst.", "traurig"),
    ("Ich kann nicht glauben, dass du das so machst!", "wütend"),
    ("Ich fühle mich wohl in dieser Umgebung.", "neutral"),
    ("Ich bin überglücklich, dass ich die Prüfung bestanden habe!", "glücklich"),
    ("Das macht mich traurig, dass du deinen Job verlierst.", "traurig"),
    ("Ich bin wütend, weil du mir nicht zuhörst.", "wütend"),
    ("Ich fühle mich neutral über das Wetter.", "neutral"),
    ("Ich freue mich, dass die Sonne scheint!", "glücklich"),
    ("Es tut mir leid, dass du so fühlst.", "traurig"),
    ("Ich kann nicht glauben, dass du das gesagt hast!", "wütend"),
    ("Ich bin zufrieden mit dem, was ich erreicht habe.", "neutral"),
    ("Ich bin so froh, dass wir uns wiedersehen!", "glücklich"),
    ("Das macht mich traurig, dass du mich ignorierst.", "traurig"),
    ("Ich bin wütend, weil das nicht fair ist.", "wütend"),
    ("Ich fühle mich ruhig, wenn ich Musik höre.", "neutral"),
    ("Ich bin glücklich über die neuen Möglichkeiten!", "glücklich"),
    ("Das ist wirklich traurig, dass du so denkst.", "traurig"),
    ("Ich bin frustriert über die ständigen Verzögerungen.", "wütend"),
    ("Ich fühle mich wohl, wenn ich mit Freunden bin.", "neutral"),
    ("Ich bin begeistert von den neuen Ideen!", "glücklich"),
    ("Das macht mich traurig, dass du nicht mehr lachen kannst.", "traurig"),
    ("Ich kann nicht glauben, dass du das gemacht hast!", "wütend"),
    ("Ich fühle mich sicher, wenn ich zu Hause bin.", "neutral"),
    ("Ich bin so froh, dass wir einen Plan haben!", "glücklich"),
    ("Das tut mir leid, dass du nicht glücklich bist.", "traurig"),
    ("Ich bin wütend, weil du meine Grenzen überschreitest.", "wütend"),
    ("Ich fühle mich stabil und gelassen.", "neutral"),
    ("Ich bin glücklich, wenn ich Zeit mit meiner Familie verbringe.", "glücklich"),
    ("Das macht mich traurig, dass wir nicht in Kontakt bleiben.", "traurig"),
    ("Ich bin wütend über die ständigen Ausreden.", "wütend"),
    ("Ich fühle mich wohl, wenn ich meditieren kann.", "neutral"),
    ("Ich finde es toll, dass wir gemeinsam arbeiten!", "glücklich"),
    ("Das ist enttäuschend, dass du nicht teilnehmen kannst.", "traurig"),
    ("Ich kann nicht glauben, dass du das gesagt hast!", "wütend"),
    ("Ich fühle mich gut, wenn ich etwas Neues lerne.", "neutral"),
    ("Ich bin so glücklich über die Unterstützung meiner Freunde!", "glücklich"),
    ("Das macht mich traurig, dass du alleine bist.", "traurig"),
    ("Ich bin frustriert über die ständigen Probleme im Team.", "wütend"),
    ("Ich fühle mich entspannt, wenn ich im Park bin.", "neutral"),
    ("Ich bin glücklich, wenn ich mit Tieren zusammen bin.", "glücklich"),
    ("Das tut mir leid zu hören, dass du leidest.", "traurig"),
    ("Ich kann nicht glauben, dass ich so enttäuscht bin!", "wütend"),
    ("Ich fühle mich zufrieden mit meinem Alltag.", "neutral"),
    ("Ich bin so froh über die Fortschritte, die ich gemacht habe!", "glücklich"),
    ("Das ist schade, dass du nicht zu meiner Feier kommen kannst.", "traurig"),
    ("Ich bin wütend, weil ich nicht ernst genommen werde.", "wütend"),
    ("Ich fühle mich gut, wenn ich kreativ bin.", "neutral"),
    ("Ich bin glücklich, dass ich meine Träume verfolge!", "glücklich"),
    ("Das macht mich traurig, dass du so oft allein bist.", "traurig"),
    ("Ich kann nicht glauben, dass du mir das antust!", "wütend"),
    ("Ich fühle mich wohl und geborgen in dieser Umgebung.", "neutral"),
    ("Ich bin glücklich, dass ich meine Ziele erreicht habe!", "glücklich"),
    ("Das macht mich traurig, dass ich nicht mit dir sein kann.", "traurig"),
    ("Ich bin wütend, weil du mich angelogen hast.", "wütend"),
    ("Ich fühle mich neutral über die aktuelle Situation.", "neutral"),
    ("Ich bin begeistert von dieser neuen Herausforderung!", "glücklich"),
    ("Es tut mir leid zu hören, dass du traurig bist.", "traurig"),
    ("Ich bin wütend, dass die Dinge nicht so laufen, wie ich es will.", "wütend"),
    ("Ich bin zufrieden mit meinem Fortschritt.", "neutral"),
    ("Ich freue mich auf das Wochenende!", "glücklich"),
    ("Das macht mich traurig, dass du mich nicht verstehst.", "traurig"),
    ("Ich kann nicht glauben, dass du das getan hast!", "wütend"),
    ("Ich fühle mich wohl in meiner Haut.", "neutral"),
    ("Ich bin glücklich, wenn ich mit Freunden zusammen bin.", "glücklich"),
    ("Das ist bedauerlich, dass du das nicht schätzt.", "traurig"),
    ("Ich bin frustriert über die ständigen Probleme.", "wütend"),
    ("Ich fühle mich entspannt, wenn ich lese.", "neutral"),
    ("Ich bin so froh, dass wir uns getroffen haben!", "glücklich"),
    ("Das macht mich traurig, dass du so oft alleine bist.", "traurig"),
    ("Ich bin wütend, weil du mir nicht zuhörst.", "wütend"),
    ("Ich fühle mich sicher in dieser Umgebung.", "neutral"),
    ("Ich bin glücklich über die Unterstützung meiner Familie.", "glücklich"),
    ("Das tut mir leid, dass du leidest.", "traurig"),
    ("Ich kann nicht glauben, dass du mich so behandelst!", "wütend"),
    ("Ich fühle mich gut, wenn ich Sport treibe.", "neutral"),
    ("Ich bin glücklich, dass der Frühling kommt!", "glücklich"),
    ("Das macht mich traurig, dass wir uns nicht mehr sehen.", "traurig"),
    ("Ich bin wütend, dass ich nicht ernst genommen werde.", "wütend"),
    ("Ich fühle mich stabil und sicher.", "neutral"),
    ("Ich bin begeistert von dem neuen Film!", "glücklich"),
    ("Das tut mir leid, dass du so fühlst.", "traurig"),
    ("Ich kann nicht glauben, dass du mir nicht vertraust!", "wütend"),
    ("Ich fühle mich entspannt, wenn ich am Meer bin.", "neutral"),
    ("Ich bin glücklich, dass ich neue Freunde gefunden habe!", "glücklich"),
    ("Das ist schade, dass du nicht kommen kannst.", "traurig"),
    ("Ich bin wütend über die ständigen Ausreden.", "wütend"),
    ("Ich fühle mich wohl, wenn ich in der Natur bin.", "neutral"),
    ("Ich bin so froh über die Fortschritte, die ich gemacht habe!", "glücklich"),
    ("Das macht mich traurig, dass du keine Zeit für mich hast.", "traurig"),
    ("Ich bin frustriert über die vielen Aufgaben.", "wütend"),
    ("Ich fühle mich sicher und geborgen.", "neutral"),
    ("Ich bin glücklich, wenn ich Zeit mit meiner Familie verbringe.", "glücklich"),
    ("Das macht mich traurig, dass du immer so negativ bist.", "traurig"),
    ("Ich kann nicht glauben, dass ich das nicht geschafft habe!", "wütend"),
    ("Ich fühle mich wohl in dieser Gemeinschaft.", "neutral"),
    ("Ich bin so glücklich, dass ich Urlaub habe!", "glücklich"),
    ("Das tut mir leid, dass du so fühlst.", "traurig"),
    ("Ich bin wütend, weil ich meine Zeit verschwende.", "wütend"),
    ("Ich fühle mich gut, wenn ich meine Ziele verfolge.", "neutral"),
    ("Ich bin glücklich, wenn ich Zeit mit meinen Freunden verbringe.", "glücklich"),
    ("Das ist wirklich bedauerlich, dass du so denkst.", "traurig"),
    ("Ich bin wütend, dass ich nicht weiterkomme.", "wütend"),
    ("Ich fühle mich entspannt, wenn ich Musik höre.", "neutral"),
    ("Ich bin so froh über die neuen Möglichkeiten!", "glücklich"),
    ("Das macht mich traurig, dass wir uns nicht mehr treffen können.", "traurig"),
    ("Ich kann nicht glauben, dass du so reagierst!", "wütend"),
    ("Ich fühle mich wohl, wenn ich Zeit für mich selbst habe.", "neutral"),
    ("Ich bin glücklich, wenn ich mit Tieren zusammen bin.", "glücklich"),
    ("Das macht mich traurig, dass du dich zurückziehst.", "traurig"),
    ("Ich bin wütend über die Ungerechtigkeit.", "wütend"),
    ("Ich fühle mich neutral über die Politik.", "neutral"),
    ("Ich bin glücklich, dass ich meine Träume verfolge!", "glücklich"),
    ("Das tut mir leid, dass du allein bist.", "traurig"),
    ("Ich bin wütend, weil ich nicht respektiert werde.", "wütend"),
    ("Ich fühle mich gut, wenn ich kreativ bin.", "neutral"),
    ("Ich bin glücklich, wenn ich etwas Neues lerne.", "glücklich"),
    ("Das macht mich traurig, dass du nicht hier bist.", "traurig"),
    ("Ich bin wütend, weil ich nicht die Anerkennung bekomme, die ich verdiene.", "wütend"),
    ("Ich fühle mich neutral über das Wetter.", "neutral"),
    ("Ich bin glücklich, dass ich an diesem Projekt arbeiten kann!", "glücklich"),
    ("Das ist schade, dass du nicht teilnehmen kannst.", "traurig"),
    ("Ich kann nicht glauben, dass du mir das gesagt hast!", "wütend"),
    ("Ich fühle mich wohl, wenn ich mit Menschen spreche.", "neutral"),
    ("Ich bin so froh, dass ich eine gute Beziehung zu meiner Familie habe.", "glücklich"),
    ("Das macht mich traurig, dass wir uns nicht mehr sehen können.", "traurig"),
    ("Ich bin wütend über die ständigen Rückschläge.", "wütend"),
    ("Ich fühle mich sicher, wenn ich bei meinen Freunden bin.", "neutral"),
    ("Ich bin glücklich, dass ich ein neues Hobby gefunden habe!", "glücklich"),
    ("Das macht mich traurig, dass du so oft unglücklich bist.", "traurig"),
    ("Ich kann nicht glauben, dass du mir das antust!", "wütend"),
    ("Ich fühle mich neutral über die aktuellen Ereignisse.", "neutral"),
    ("Ich bin glücklich, wenn ich die Natur genieße.", "glücklich"),
    ("Das tut mir leid, dass du so denkst.", "traurig"),
    ("Ich bin wütend, weil ich nicht die Kontrolle habe.", "wütend"),
    ("Ich fühle mich gut, wenn ich mit Menschen zusammenarbeite.", "neutral"),
    ("Ich bin glücklich, dass ich neue Abenteuer erlebe!", "glücklich"),
    ("Das macht mich traurig, dass du dich so fühlst.", "traurig"),
    ("Ich kann nicht fassen, dass du mich so behandelst!", "wütend"),
    ("Ich fühle mich neutral über die aktuelle politische Lage.", "neutral"),
    ("Ich bin glücklich, wenn ich bei meinen Freunden bin.", "glücklich"),
    ("Das macht mich traurig, dass du nie lächelst.", "traurig"),
    ("Ich bin wütend über die ständigen Lügen.", "wütend"),
    ("Ich fühle mich unsicher in großen Gruppen.", "ängstlich"),
    ("Ich bin ängstlich, wenn ich an die Zukunft denke.", "ängstlich"),
    ("Ich bin ängstlich, dass ich nicht gut genug bin.", "ängstlich"),
    ("Ich fühle mich ängstlich, wenn ich eine Präsentation halten muss.", "ängstlich"),
    ("Ich bin ängstlich, wenn ich in unbekannte Situationen gehe.", "ängstlich"),
    ("Ich fühle mich ängstlich, wenn ich neue Menschen treffe.", "ängstlich"),
    ("Ich bin ängstlich, dass ich nicht rechtzeitig fertig werde.", "ängstlich"),
    ("Ich fühle mich ängstlich, wenn ich allein zu Hause bin.", "ängstlich"),
    ("Ich bin ängstlich, dass ich nicht die richtige Entscheidung treffe.", "ängstlich"),
    ("Ich fühle mich ängstlich, wenn ich über meine Zukunft nachdenke.", "ängstlich"),
    ("Ich bin ängstlich, wenn ich vor einer großen Gruppe sprechen muss.", "ängstlich"),
    ("Ich fühle mich ängstlich, wenn ich an Veränderungen denke.", "ängstlich"),
    ("Ich bin so glücklich, dass ich meine Familie sehe!", "glücklich"),
    ("Es macht mich traurig, dass wir uns nicht oft sehen können.", "traurig"),
    ("Ich bin wütend, weil ich nicht die nötige Hilfe bekomme.", "wütend"),
    ("Ich fühle mich neutral über das Ergebnis der Wahl.", "neutral"),
    ("Ich bin glücklich, wenn ich Zeit mit meinen Freunden verbringe.", "glücklich"),
    ("Das macht mich traurig, dass du so oft alleine bist.", "traurig"),
    ("Ich bin frustriert über die ständigen Unterbrechungen.", "wütend"),
    ("Ich fühle mich neutral, wenn ich über das Wetter nachdenke.", "neutral"),
    ("Ich freue mich, dass ich eine neue Stelle gefunden habe!", "glücklich"),
    ("Es tut mir leid, dass du so fühlst.", "traurig"),
    ("Ich kann nicht glauben, dass du das getan hast!", "wütend"),
     ("Ich fühle mich ängstlich, wenn ich eine Prüfung habe.", "ängstlich"),
    ("Ich bin ängstlich, wenn ich in ein Flugzeug steige.", "ängstlich"),
    ("Ich fühle mich ängstlich, wenn ich nachts alleine unterwegs bin.", "ängstlich"),
    ("Ich bin ängstlich, wenn ich eine wichtige Entscheidung treffen muss.", "ängstlich"),
    ("Ich fühle mich ängstlich, wenn ich an meine Zukunft denke.", "ängstlich"),
    ("Ich bin ängstlich, weil ich nicht weiß, was passieren wird.", "ängstlich"),
    ("Ich fühle mich ängstlich, wenn ich in einem neuen Umfeld bin.", "ängstlich"),
    ("Ich bin ängstlich, wenn ich vor Publikum sprechen muss.", "ängstlich"),
    ("Ich fühle mich ängstlich, wenn ich eine schwierige Aufgabe vor mir habe.", "ängstlich"),
    ("Ich bin so glücklich, dass ich meine Prüfung bestanden habe!", "glücklich"),
    ("Es macht mich traurig, wenn jemand unfair behandelt wird.", "traurig"),
    ("Ich bin wütend, weil ich mein Ziel nicht erreicht habe.", "wütend"),
    ("Ich fühle mich neutral gegenüber dieser Entscheidung.", "neutral"),
    ("Ich bin glücklich, wenn ich gute Nachrichten bekomme.", "glücklich"),
    ("Das macht mich traurig, wenn ich an die Vergangenheit denke.", "traurig"),
    ("Ich bin frustriert, wenn die Technik nicht funktioniert.", "wütend"),
    ("Ich fühle mich neutral, wenn ich über meinen Alltag nachdenke.", "neutral"),
    ("Ich freue mich, dass ich bald in den Urlaub fahre!", "glücklich"),
    ("Es tut mir leid, dass du dich so fühlst.", "traurig"),
    ("Ich kann nicht glauben, dass das wirklich passiert ist!", "wütend"),
    ("Ich fühle mich ängstlich, wenn ich allein in der Dunkelheit bin.", "ängstlich"),
    ("Ich bin ängstlich, dass ich einen Fehler mache.", "ängstlich"),
    ("Ich fühle mich ängstlich, wenn ich mich unvorbereitet fühle.", "ängstlich"),
    ("Ich bin ängstlich, wenn ich etwas Neues ausprobieren muss.", "ängstlich"),
    ("Ich fühle mich ängstlich, wenn ich eine schwierige Entscheidung treffen muss.", "ängstlich"),
    ("Ich bin glücklich, wenn ich ein schönes Geschenk bekomme.", "glücklich"),
    ("Es macht mich traurig, wenn ich an schlechte Zeiten denke.", "traurig"),
    ("Ich bin wütend, wenn ich im Stau stehe.", "wütend"),
    ("Ich fühle mich neutral gegenüber diesem Thema.", "neutral"),
    ("Ich bin glücklich, wenn ich einen schönen Tag mit meiner Familie verbringe.", "glücklich"),
    ("Das macht mich traurig, wenn jemand mich enttäuscht.", "traurig"),
    ("Ich bin frustriert, wenn ich lange warten muss.", "wütend"),
    ("Ich fühle mich neutral, wenn ich an meinen Job denke.", "neutral"),
    ("Ich freue mich, dass ich neue Leute kennengelernt habe!", "glücklich"),
    ("Es tut mir leid, dass du diese Erfahrung machen musst.", "traurig"),
    ("Ich kann nicht glauben, dass das so lange dauert!", "wütend"),
    ("Ich fühle mich ängstlich, wenn ich einen Arzttermin habe.", "ängstlich"),
    ("Ich bin ängstlich, wenn ich eine Präsentation halten muss.", "ängstlich"),
    ("Ich fühle mich ängstlich, wenn ich an meine Zukunft denke.", "ängstlich"),
    ("Ich bin ängstlich, wenn ich eine neue Herausforderung annehme.", "ängstlich"),
    ("Ich fühle mich ängstlich, wenn ich nicht weiß, was als Nächstes kommt.", "ängstlich"),
    ("Ich bin glücklich, wenn ich eine gute Zeit mit Freunden habe.", "glücklich"),
    ("Es macht mich traurig, wenn ich alleine essen muss.", "traurig"),
    ("Ich bin wütend, wenn jemand unhöflich ist.", "wütend"),
    ("Ich fühle mich neutral, wenn ich meine täglichen Aufgaben erledige.", "neutral"),
    ("Ich bin glücklich, wenn ich ein gutes Buch lese.", "glücklich"),
    ("Das macht mich traurig, wenn ich jemanden vermisse.", "traurig"),
    ("Ich bin frustriert, wenn mein Internet langsam ist.", "wütend"),
    ("Ich fühle mich neutral, wenn ich über mein Wochenende nachdenke.", "neutral"),

    ("Ich fühle mich entspannt, wenn ich einen Spaziergang mache.", "neutral"),
    ("Ich bin glücklich über die Erfolge, die ich erreicht habe!", "glücklich"),
    ("Das ist schade, dass du nicht mehr Zeit hast.", "traurig"),
    ("Ich bin wütend, weil ich unfair behandelt werde.", "wütend"),
    ("Ich fühle mich neutral in Bezug auf die aktuelle Situation.", "neutral"),
    ("Ich bin glücklich, wenn ich meine Lieblingsmusik höre.", "glücklich"),
    ("Es macht mich traurig, dass du mir nicht vertraust.", "traurig"),
    ("Ich bin wütend über die ständigen Verspätungen.", "wütend"),
    ("Ich fühle mich wohl, wenn ich in der Natur bin.", "neutral"),
    ("Ich bin so froh, dass ich meine Prüfung bestanden habe!", "glücklich"),
    ("Das tut mir leid, dass du nicht glücklich bist.", "traurig"),
    ("Ich kann nicht glauben, dass ich das vergessen habe!", "wütend"),
    ("Ich fühle mich entspannt, wenn ich meditiere.", "neutral"),
    ("Ich bin glücklich über die Unterstützung, die ich bekomme.", "glücklich"),
    ("Das macht mich traurig, dass du nicht mehr lächelst.", "traurig"),
    ("Ich bin wütend, weil ich nicht die Anerkennung bekomme, die ich verdiene.", "wütend"),
    ("Ich fühle mich stabil und sicher in meinem Leben.", "neutral"),
    ("Ich bin glücklich, dass ich meine Träume verfolgen kann!", "glücklich"),
    ("Das ist wirklich bedauerlich, dass du das so siehst.", "traurig"),
    ("Ich bin frustriert über die ständigen Probleme im Team.", "wütend"),
    ("Ich fühle mich wohl, wenn ich mit Freunden zusammen bin.", "neutral"),
    ("Ich bin glücklich über die neuen Möglichkeiten, die sich ergeben!", "glücklich"),
    ("Das macht mich traurig, dass du nicht mehr lachen kannst.", "traurig"),
    ("Ich kann nicht glauben, dass ich so viel Zeit verloren habe!", "wütend"),
    ("Ich fühle mich neutral über das, was passiert ist.", "neutral"),
    ("Ich bin so froh, dass ich die Chance habe, zu reisen!", "glücklich"),
    ("Das tut mir leid zu hören, dass du leidest.", "traurig"),
    ("Ich bin wütend, dass ich nicht mehr Zeit für mich selbst habe.", "wütend"),
    ("Ich fühle mich gut, wenn ich an meinen Zielen arbeite.", "neutral"),
    ("Ich bin glücklich, wenn ich neue Dinge lerne!", "glücklich"),
    ("Das macht mich traurig, dass du nicht mehr hier bist.", "traurig"),
    ("Ich bin wütend über die Ungerechtigkeit, die ich sehe.", "wütend"),
    ("Ich fühle mich neutral über die aktuelle Diskussion.", "neutral"),
    ("Ich bin glücklich, wenn ich mit meiner Familie zusammen bin.", "glücklich"),
    ("Das ist schade, dass du nicht teilnehmen kannst.", "traurig"),
    ("Ich kann nicht glauben, dass du so reagierst!", "wütend"),
    ("Ich fühle mich wohl in dieser Umgebung.", "neutral"),
    ("Ich bin glücklich, dass ich an diesem Projekt teilnehmen kann!", "glücklich"),
    ("Das macht mich traurig, dass du nicht mehr optimistisch bist.", "traurig"),
    ("Ich bin wütend, weil ich immer wieder enttäuscht werde.", "wütend"),
    ("Ich fühle mich sicher, wenn ich meine Freunde um mich habe.", "neutral"),
    ("Ich fühle mich neutral über die Nachrichten heute.", "neutral"),
    ("Das Wetter ist in Ordnung, aber nicht besonders.", "neutral"),
    ("Ich bin mir nicht sicher, wie ich über die Situation denken soll.", "neutral"),
    ("Ich empfinde nichts Besonderes, wenn ich darüber nachdenke.", "neutral"),
    ("Es ist ein normaler Tag für mich.", "neutral"),
    ("Ich fühle mich ruhig und gelassen.", "neutral"),
    ("Ich habe keine starken Meinungen zu diesem Thema.", "neutral"),
    ("Ich sehe die Dinge so, wie sie sind.", "neutral"),
    ("Ich bin neutral, wenn es um Politik geht.", "neutral"),
    ("Ich habe keine besonderen Gefühle zu den Ergebnissen.", "neutral"),
    ("Ich nehme die Dinge, wie sie kommen.", "neutral"),
    ("Ich habe mich daran gewöhnt, dass nicht alles perfekt ist.", "neutral"),
    ("Ich fühle mich ausgeglichen und ruhig.", "neutral"),
    ("Ich habe keine starken Emotionen über das aktuelle Geschehen.", "neutral"),
    ("Ich genieße einfach den Moment.", "neutral"),
    ("Ich fühle mich indifferent über das, was andere sagen.", "neutral"),
    ("Es ist einfach ein weiterer Tag im Leben.", "neutral"),
    ("Ich bin weder aufgeregt noch enttäuscht.", "neutral"),
    ("Ich habe keine spezielle Meinung über das Thema.", "neutral"),
    ("Ich bin unentschlossen, was die nächsten Schritte angeht.", "neutral"),
    ("Ich kann die Situation objektiv betrachten.", "neutral"),
    ("Ich habe nichts dagegen, aber ich bin auch nicht begeistert.", "neutral"),
    ("Ich nehme die Herausforderungen an, ohne große Erwartungen.", "neutral"),
    ("Ich fühle mich neutral über meine Entscheidungen.", "neutral"),
    ("Ich beobachte die Dinge, ohne emotional zu reagieren.", "neutral"),
    ("Ich akzeptiere die Realität, wie sie ist.", "neutral"),
    ("Ich sehe das Positive und Negative in allem.", "neutral"),
    ("Ich finde die Diskussion interessant, aber nicht emotional.", "neutral"),
    ("Ich bin in einer neutralen Stimmung heute.", "neutral"),
    ("Ich habe keine speziellen Wünsche oder Bedürfnisse.", "neutral"),
    ("Ich kann die Meinungen anderer respektieren, ohne mich zu engagieren.", "neutral"),
    ("Ich fühle mich wohl, ohne große Erwartungen.", "neutral"),
    ("Ich bin bereit, die Situation zu akzeptieren, wie sie ist.", "neutral"),
    ("Ich bin entspannt und offen für alles.", "neutral"),
    ("Ich finde es interessant, aber nicht aufregend.", "neutral"),
    ("Ich habe eine gelassene Haltung gegenüber Veränderungen.", "neutral"),
    ("Ich bin neutral in Bezug auf die neuen Entwicklungen.", "neutral"),
    ("Ich bin nicht besonders begeistert oder enttäuscht.", "neutral"),
    ("Ich kann mich nicht entscheiden, was ich denken soll.", "neutral"),
    ("Ich nehme die Informationen einfach zur Kenntnis.", "neutral"),
    ("Ich fühle mich stabil und ausgeglichen.", "neutral"),
    ("Ich habe keine Vorurteile gegenüber dem Thema.", "neutral"),
    ("Ich bleibe unberührt von den Diskussionen.", "neutral"),
    ("Ich bin neugierig, aber nicht emotional investiert.", "neutral"),
    ("Ich betrachte die Dinge mit einer neutralen Perspektive.", "neutral"),
    ("Ich bin aufgeschlossen, aber nicht gefühlsmäßig involviert.", "neutral"),
    ("Ich habe nichts zu verlieren oder zu gewinnen.", "neutral"),
    ("Ich fühle mich neutral in der aktuellen Lage.", "neutral"),
    ("Ich finde die Idee interessant, ohne dass sie mich bewegt.", "neutral"),
    ("Ich kann die Fakten klar sehen, ohne Emotionen.", "neutral"),
    ("Ich bin zufrieden mit dem, was ich habe.", "neutral"),
    ("Ich bin bereit, zuzuhören, ohne voreingenommen zu sein.", "neutral"),
    ("Ich bin entspannt und lasse die Dinge geschehen.", "neutral"),
    ("Ich habe keine emotionale Reaktion auf die Situation.", "neutral"),
    ("Ich fühle mich wohl in meinem aktuellen Zustand.", "neutral"),
    ("Ich bin offen für neue Informationen, ohne Vorurteile.", "neutral"),
    ("Ich genieße die Stille, ohne darüber nachzudenken.", "neutral"),
    ("Ich sehe die Dinge, wie sie sind, ohne Verzerrungen.", "neutral"),
    ("Ich habe keine starke Meinung über die gegenwärtige Lage.", "neutral"),
    ("Ich bin indifferent gegenüber dem Ergebnis.", "neutral"),
    ("Ich beobachte die Veränderungen, ohne mich zu engagieren.", "neutral"),
    ("Ich akzeptiere die Realität ohne Widerstand.", "neutral"),
    ("Ich bin nicht besorgt über die Zukunft.", "neutral"),
    ("Ich fühle mich neutral über die verschiedenen Meinungen.", "neutral"),
    ("Ich bin entspannt, ohne Erwartungen.", "neutral"),
    ("Ich akzeptiere alles, was kommt.", "neutral"),
    ("Ich bin bereit, neue Perspektiven zu hören.", "neutral"),
    ("Ich genieße die Einfachheit des Alltags.", "neutral"),
    ("Ich finde es angenehm, ohne viel Aufregung.", "neutral"),
    ("Ich bin nicht betroffen von den äußeren Umständen.", "neutral"),
    ("Ich fühle mich neutral in Bezug auf die Menschen um mich herum.", "neutral"),
    ("Ich kann die Diskussionen verfolgen, ohne mich emotional zu engagieren.", "neutral"),
    ("Ich bin gelassen und offen für alles, was kommt.", "neutral"),
    ("Ich habe keine besonderen Wünsche für die Zukunft.", "neutral"),
    ("Ich bin bereit, die Dinge so zu akzeptieren, wie sie sind.", "neutral"),
    ("Ich fühle mich ausgeglichen und zufrieden.", "neutral"),
    ("Ich habe keine starken Emotionen über die Veränderungen.", "neutral"),
    ("Ich bleibe ruhig in herausfordernden Situationen.", "neutral"),
    ("Ich nehme das Leben wie es kommt.", "neutral"),
    ("Ich fühle mich wohl, ohne viel nachzudenken.", "neutral"),
    ("Ich beobachte die Dinge mit Interesse, aber ohne Aufregung.", "neutral"),
    ("Ich bin offen für neue Ideen, ohne voreingenommen zu sein.", "neutral"),
    ("Ich genieße die Ruhe ohne Ablenkung.", "neutral"),
    ("Ich bin gelassen und freue mich auf das, was kommt.", "neutral"),
    ("Ich finde die Entwicklung interessant, aber nicht emotional.", "neutral"),
    ("Ich fühle mich wohl in meiner eigenen Haut.", "neutral"),
    ("Ich bin zufrieden mit meinem aktuellen Zustand.", "neutral"),
    ("Ich kann die Meinungen anderer respektieren, ohne mich zu engagieren.", "neutral"),
    ("Ich bin neutral über die Diskussion.", "neutral"),
    ("Ich bin voller Freude!", "glücklich"),
    ("Das macht mich unglaublich traurig.", "traurig"),
    ("Ich bin wirklich wütend über diese Situation.", "wütend"),
    ("Ich fühle mich vollkommen entspannt.", "neutral"),
    ("Ich liebe es, neue Orte zu entdecken!", "glücklich"),
    ("Es bricht mir das Herz, das zu hören.", "traurig"),
    ("Ich bin sauer, weil du dein Versprechen gebrochen hast.", "wütend"),
    ("Ich bin zufrieden mit meinem Leben.", "neutral"),
    ("Ich bin so froh, dass wir gewonnen haben!", "glücklich"),
    ("Das ist wirklich deprimierend für mich.", "traurig"),
     ("Ich bin überglücklich mit meinem neuen Job!", "glücklich"),
    ("Das ist einfach nur deprimierend.", "traurig"),
    ("Ich bin so wütend über diese Ungerechtigkeit!", "wütend"),
    ("Ich fühle mich entspannt und frei.", "neutral"),
    ("Ich liebe es, neue Dinge zu entdecken!", "glücklich"),
    ("Es macht mich traurig, wenn du mich ignorierst.", "traurig"),
    ("Ich bin frustriert über den ständigen Lärm.", "wütend"),
    ("Ich genieße die Stille nach einem langen Tag.", "neutral"),
    ("Ich bin so glücklich über diese tolle Nachricht!", "glücklich"),
    ("Das ist wirklich herzzerreißend.", "traurig"),
    ("Ich kann nicht fassen, wie unfair das ist!", "wütend"),
    ("Ich bin einfach zufrieden mit meinem Leben.", "neutral"),
    ("Ich freue mich auf unser Treffen!", "glücklich"),
    ("Das ist wirklich schwer für mich.", "traurig"),
    ("Ich bin verärgert über die schlechten Entscheidungen.", "wütend"),
    ("Ich fühle mich ausgeglichen und ruhig.", "neutral"),
    ("Ich bin begeistert von dieser Idee!", "glücklich"),
    ("Es tut mir leid, dass du dich so fühlst.", "traurig"),
    ("Ich bin wütend, dass niemand zuhört!", "wütend"),
    ("Ich bin froh, dass ich heute Zeit für mich habe.", "neutral"),
    ("Ich bin so glücklich, dass ich das erleben darf!", "glücklich"),
    ("Das bricht mir das Herz.", "traurig"),
    ("Ich bin so wütend auf diese Situation!", "wütend"),
    ("Ich fühle mich in meiner Haut wohl.", "neutral"),
    ("Ich bin dankbar für meine Familie und Freunde.", "glücklich"),
    ("Das ist wirklich eine schreckliche Nachricht.", "traurig"),
    ("Ich bin enttäuscht von der Reaktion.", "wütend"),
    ("Ich bin ruhig und gelassen.", "neutral"),
    ("Ich freue mich auf die kommende Woche!", "glücklich"),
    ("Das ist so traurig, dass ich nicht weiß, was ich sagen soll.", "traurig"),
    ("Ich bin extrem genervt von dem Verhalten.", "wütend"),
    ("Ich genieße den Moment.", "neutral"),
    ("Ich liebe es, wenn die Sonne scheint!", "glücklich"),
    ("Das macht mich sehr emotional.", "traurig"),
    ("Ich bin wirklich sauer auf diese Entscheidung!", "wütend"),
    ("Ich fühle mich frei und leicht.", "neutral"),
    ("Ich bin stolz auf mich!", "glücklich"),
    ("Das ist ein wirklich trauriger Tag.", "traurig"),
    ("Ich kann nicht glauben, dass das schon wieder passiert!", "wütend"),
    ("Ich bin in Frieden mit mir selbst.", "neutral"),
    ("Ich bin glücklich, dass ich neue Dinge lernen kann.", "glücklich"),
    ("Das hat mich tief getroffen.", "traurig"),
    ("Ich bin richtig frustriert über diesen Fehler!", "wütend"),
    ("Ich fühle mich neutral über diese Entscheidung.", "neutral"),
    ("Ich bin begeistert von diesem Abenteuer!", "glücklich"),
    ("Das ist eine wirklich harte Zeit für mich.", "traurig"),
    ("Ich kann nicht glauben, wie unfair das ist!", "wütend"),
    ("Ich bin einfach nur zufrieden mit dem, was ich habe.", "neutral"),
    ("Ich bin unglaublich glücklich über diese Möglichkeit!", "glücklich"),
    ("Das ist wirklich schwer zu verkraften.", "traurig"),
    ("Ich bin sauer, dass meine Meinung ignoriert wurde.", "wütend"),

    ("Ich kann nicht glauben, dass du so gemein warst!", "wütend"),
    ("Ich fühle mich heute ganz gelassen.", "neutral"),
    ("Ich bin begeistert von dieser Neuigkeit!", "glücklich"),
    ("Das macht mich innerlich sehr traurig.", "traurig"),
    ("Ich bin wütend über die Unhöflichkeit.", "wütend"),
    ("Ich fühle mich weder gut noch schlecht.", "neutral"),
    ("Ich bin glücklich, wenn ich meine Freunde treffe.", "glücklich"),
    ("Das war wirklich enttäuschend.", "traurig"),
    ("Ich bin so verärgert über diese Ungerechtigkeit!", "wütend"),
    ("Ich genieße die Stille.", "neutral"),
    ("Ich bin so glücklich, dass alles geklappt hat!", "glücklich"),
    ("Das macht mich tief betroffen.", "traurig"),
    ("Ich bin wütend über die Lügen.", "wütend"),
    ("Ich fühle mich einfach normal.", "neutral"),
    ("Ich liebe den Sonnenschein!", "glücklich"),
    ("Das ist eine traurige Geschichte.", "traurig"),
    ("Ich kann nicht fassen, dass ich verloren habe!", "wütend"),
    ("Ich fühle mich ruhig und ausgeglichen.", "neutral"),
    ("Ich bin glücklich über die guten Nachrichten.", "glücklich"),
    ("Das hat mich sehr getroffen.", "traurig"),
    ("Ich bin wütend, dass du mir nicht zuhörst.", "wütend"),
    ("Ich bin entspannt und genieße den Moment.", "neutral"),
    ("Ich bin aufgeregt wegen der Reise!", "glücklich"),
    ("Das ist wirklich eine Tragödie.", "traurig"),
    ("Ich bin wütend auf diese Ungerechtigkeit.", "wütend"),
    ("Ich fühle mich neutral gegenüber der Situation.", "neutral"),
    ("Ich bin überglücklich über die Neuigkeiten!", "glücklich"),
    ("Es ist schwer, so etwas zu verkraften.", "traurig"),
    ("Ich bin enttäuscht über das Verhalten.", "wütend"),
    ("Ich bin in einer friedlichen Stimmung.", "neutral"),
    ("Ich bin froh, dass ich heute hier sein kann.", "glücklich"),
    ("Das macht mich tieftraurig.", "traurig"),
    ("Ich bin wütend auf den Verkehr.", "wütend"),
    ("Ich fühle mich zufrieden.", "neutral"),
    ("Ich bin voller Energie und Glück!", "glücklich"),
    ("Das ist eine wirklich schlimme Nachricht.", "traurig"),
    ("Ich kann nicht glauben, dass das passiert ist!", "wütend"),
    ("Ich bin einfach nur ruhig und entspannt.", "neutral"),
    ("Ich bin begeistert von dieser Idee!", "glücklich"),
    ("Das ist wirklich herzzerreißend.", "traurig"),
    ("Ich könnte vor Freude tanzen!", "glücklich"),
    ("Ich bin einfach nur enttäuscht.", "traurig"),
    ("Ich bin stinksauer!", "wütend"),
    ("Mir geht es heute ganz normal.", "neutral"),
    ("Das ist der beste Tag meines Lebens!", "glücklich"),
    ("Ich fühle mich leer und hoffnungslos.", "traurig"),
    ("Ich bin so wütend, dass ich schreien könnte!", "wütend"),
    ("Ich empfinde gar nichts dabei.", "neutral"),
    ("Ich bin unglaublich stolz auf dich!", "glücklich"),
    ("Ich kann einfach nicht aufhören zu weinen.", "traurig"),
    ("Ich hasse es, wenn das passiert!", "wütend"),
    ("Ich bin in einer entspannten Stimmung.", "neutral"),
    ("Ich bin so glücklich, dass ich lachen muss!", "glücklich"),
    ("Ich fühle mich heute wirklich niedergeschlagen.", "traurig"),
    ("Ich bin so sauer, dass ich es nicht in Worte fassen kann!", "wütend"),
    ("Ich spüre eine völlige innere Ruhe.", "neutral"),
    ("Ich liebe mein Leben!", "glücklich"),
    ("Nichts macht mich mehr traurig als Verrat.", "traurig"),
    ("Ich bin einfach nur frustriert.", "wütend"),
    ("Ich fühle mich ziemlich ausgeglichen.", "neutral"),
    ("Ich bin so aufgeregt für morgen!", "glücklich"),
    ("Das bricht mir das Herz.", "traurig"),
    ("Ich kann diese Ungerechtigkeit nicht ertragen!", "wütend"),
    ("Ich habe keine besondere Stimmung.", "neutral"),
    ("Ich bin so froh, dich zu sehen!", "glücklich"),
    ("Es fühlt sich an, als würde mein Herz zerbrechen.", "traurig"),
    ("Ich bin unglaublich genervt von dieser Situation!", "wütend"),
    ("Ich bin weder glücklich noch traurig.", "neutral"),
    ("Ich bin so dankbar für alles!", "glücklich"),
    ("Das Leben fühlt sich gerade so schwer an.", "traurig"),
    ("Ich bin völlig außer mir vor Wut!", "wütend"),
    ("Ich habe eine neutrale Einstellung dazu.", "neutral"),
    ("Ich bin voller Freude und Energie!", "glücklich"),
    ("Ich fühle mich einsam und verlassen.", "traurig"),
    ("Ich bin einfach nur gereizt!", "wütend"),
    ("Ich empfinde nichts Besonderes.", "neutral"),
    ("Ich liebe es, Zeit mit meiner Familie zu verbringen!", "glücklich"),
    ("Ich bin zutiefst enttäuscht.", "traurig"),
    ("Ich hasse es, wenn Leute mich belügen!", "wütend"),
    ("Ich fühle mich weder gut noch schlecht.", "neutral"),
    ("Ich bin so froh über diese Überraschung!", "glücklich"),
    ("Mein Herz ist schwer vor Trauer.", "traurig"),
    ("Ich bin so genervt von diesem Lärm!", "wütend"),
    ("Ich nehme die Dinge, wie sie kommen.", "neutral"),
    ("Ich bin auf Wolke sieben!", "glücklich"),
    ("Ich habe gerade keine Kraft mehr.", "traurig"),
    ("Ich bin einfach nur wütend auf mich selbst.", "wütend"),
    ("Ich bin in einer ruhigen, gelassenen Stimmung.", "neutral"),
    ("Ich liebe es, neue Dinge auszuprobieren!", "glücklich"),
    ("Ich fühle mich verloren und verwirrt.", "traurig"),
     ("Ich bin überglücklich, dass ich den Job bekommen habe!", "glücklich"),
    ("Es macht mich traurig, dass wir uns so selten sehen.", "traurig"),
    ("Ich bin wütend, wenn jemand mich unterbricht.", "wütend"),
    ("Ich fühle mich neutral, wenn ich Nachrichten lese.", "neutral"),
    ("Ich freue mich riesig auf meinen Geburtstag!", "glücklich"),
    ("Ich bin enttäuscht, dass mein Team verloren hat.", "traurig"),
    ("Ich bin genervt, wenn ich im Stau stehe.", "wütend"),
    ("Ich bin unentschlossen über meine nächste Reise.", "neutral"),
    ("Ich bin so stolz auf meine Fortschritte!", "glücklich"),
    ("Es macht mich traurig, wenn ich alte Fotos anschaue.", "traurig"),
    ("Ich bin wütend, wenn meine Arbeit nicht gewürdigt wird.", "wütend"),
    ("Ich fühle mich neutral, wenn ich neue Leute treffe.", "neutral"),
    ("Ich liebe es, wenn die Sonne scheint!", "glücklich"),
    ("Ich bin deprimiert, wenn es den ganzen Tag regnet.", "traurig"),
    ("Ich bin fassungslos über diese Ungerechtigkeit!", "wütend"),
    ("Ich bin unsicher, ob ich die richtige Wahl getroffen habe.", "neutral"),
    ("Ich bin voller Energie nach einem guten Schlaf!", "glücklich"),
    ("Es macht mich traurig, wenn meine Lieblingsserie endet.", "traurig"),
    ("Ich bin sauer, weil meine Bestellung falsch geliefert wurde.", "wütend"),
    ("Ich fühle mich ausgeglichen nach einer Meditation.", "neutral"),
    ("Ich bin total begeistert von diesem Film!", "glücklich"),
    ("Ich fühle mich niedergeschlagen, wenn ich an die Vergangenheit denke.", "traurig"),
    ("Ich bin verärgert über die schlechten Serviceleistungen.", "wütend"),
    ("Ich habe keine starke Meinung zu diesem Thema.", "neutral"),
    ("Ich könnte vor Freude tanzen!", "glücklich"),
    ("Ich bin am Boden zerstört über diese Nachricht.", "traurig"),
    ("Ich bin gereizt, wenn ich hungrig bin.", "wütend"),
    ("Ich bin zwiegespalten über diese Entscheidung.", "neutral"),
    ("Ich bin so glücklich über meine neuen Schuhe!", "glücklich"),
    ("Es zerreißt mir das Herz, dich weinen zu sehen.", "traurig"),
    ("Ich bin empört über diese Lüge!", "wütend"),
    ("Ich bin indifferent gegenüber diesem Vorschlag.", "neutral"),
    ("Ich bin überglücklich, dass ich ein tolles Geschenk bekommen habe!", "glücklich"),
    ("Ich fühle mich niedergeschlagen nach einer schlechten Nachricht.", "traurig"),
    ("Ich bin aufgebracht, wenn jemand meine Sachen ohne Erlaubnis nimmt.", "wütend"),
    ("Ich habe keine starke Meinung über dieses Buch.", "neutral"),
    ("Ich bin total euphorisch nach einem erfolgreichen Tag!", "glücklich"),
    ("Ich fühle mich hoffnungslos, wenn ich keine Lösung sehe.", "traurig"),
    ("Ich bin genervt von lauten Nachbarn.", "wütend"),
    ("Ich fühle mich neutral gegenüber diesem neuen Kollegen.", "neutral"),
    ("Ich bin so glücklich, dass ich ein Konzert besuchen kann!", "glücklich"),
    ("Ich bin melancholisch, wenn ich an alte Zeiten denke.", "traurig"),
    ("Ich bin frustriert, wenn mein Computer abstürzt.", "wütend"),
    ("Ich fühle mich ausgeglichen nach einer Yoga-Session.", "neutral"),
    ("Ich bin ekstatisch über meine neuen Errungenschaften!", "glücklich"),
    ("Ich bin betrübt, wenn ein geliebter Mensch leidet.", "traurig"),
    ("Ich bin erzürnt, wenn ich betrogen werde.", "wütend"),
    ("Ich bin unbeteiligt an dieser Diskussion.", "neutral"),
    ("Ich bin außer mir vor Freude!", "glücklich"),
    ("Ich bin bedrückt, wenn ich an die Zukunft denke.", "traurig"),
    ("Ich bin ärgerlich, wenn ich missverstanden werde.", "wütend"),
    ("Ich bin unglaublich glücklich über meine Beförderung!", "glücklich"),
    ("Es bricht mir das Herz, dass du so traurig bist.", "traurig"),
    ("Ich bin wütend, weil mein Handy nicht funktioniert.", "wütend"),
    ("Ich fühle mich neutral über den heutigen Tag.", "neutral"),
    ("Ich bin überglücklich, dass ich meine Prüfung bestanden habe!", "glücklich"),
    ("Ich bin traurig, weil mein Lieblingscafé geschlossen hat.", "traurig"),
    ("Ich bin verärgert, wenn jemand unhöflich ist.", "wütend"),
    ("Ich bin gleichgültig gegenüber dieser Diskussion.", "neutral"),
    ("Ich bin euphorisch nach meinem großen Erfolg!", "glücklich"),
    ("Es macht mich traurig, wenn ich an verlorene Freundschaften denke.", "traurig"),
    ("Ich bin wütend, wenn ich ungerecht behandelt werde.", "wütend"),
    ("Ich bin unsicher, was ich tun soll.", "neutral"),
    ("Ich bin so froh, dass ich eine Reise machen kann!", "glücklich"),
    ("Ich fühle mich melancholisch, wenn ich alte Briefe lese.", "traurig"),
    ("Ich bin genervt von dem Lärm draußen.", "wütend"),
    ("Ich bin unentschlossen über meine nächste Entscheidung.", "neutral"),
    ("Ich bin ekstatisch über mein neues Auto!", "glücklich"),
    ("Ich bin traurig, dass mein Urlaub vorbei ist.", "traurig"),
    ("Ich bin frustriert, wenn ich lange warten muss.", "wütend"),
    ("Ich bin unbeteiligt an diesem Gespräch.", "neutral"),
    ("Ich bin voller Freude über meine neuen Freunde!", "glücklich"),
    ("Ich fühle mich deprimiert nach einer schlechten Nachricht.", "traurig"),
    ("Ich bin wütend, wenn jemand mich anlügt.", "wütend"),
    ("Ich bin ausgeglichen nach einer Meditation.", "neutral"),
    ("Ich bin glücklich, weil ich heute viel gelacht habe!", "glücklich"),
    ("Ich bin tieftraurig über den Verlust meines Haustieres.", "traurig"),
    ("Ich bin empört über diese Ungerechtigkeit!", "wütend"),
    ("Ich bin indifferent gegenüber den neuesten Modetrends.", "neutral"),
    ("Ich bin begeistert, dass ich ein neues Hobby gefunden habe!", "glücklich"),
    ("Ich bin niedergeschlagen, weil ich eine schlechte Note bekommen habe.", "traurig"),
    ("Ich bin genervt, wenn jemand laut telefoniert.", "wütend"),
    ("Ich bin neutral gegenüber diesem Film.", "neutral"),
    ("Ich bin überglücklich, dass ich meine Familie bald sehe!", "glücklich"),
    ("Ich bin enttäuscht, weil mein Lieblingsladen geschlossen hat.", "traurig"),
    ("Ich bin zornig, wenn ich unfair behandelt werde.", "wütend"),
    ("Ich bin gleichgültig gegenüber diesem Thema.", "neutral"),
    ("Ich bin glücklich, dass ich heute produktiv war!", "glücklich"),
    ("Ich fühle mich bedrückt nach einem Streit.", "traurig"),
    ("Ich bin verärgert, wenn ich mein Passwort vergesse.", "wütend"),
    ("Ich bin gelassen nach einer langen Wanderung.", "neutral"),
    ("Ich bin voller Glück, weil ich meine Lieblingsband live sehe!", "glücklich"),
    ("Ich bin traurig, dass es heute den ganzen Tag regnet.", "traurig"),
    ("Ich bin erzürnt über die Verspätung meines Zuges.", "wütend"),
    ("Ich bin neutral gegenüber dieser neuen Regelung.", "neutral"),
    ("Ich bin total aufgeregt über meinen neuen Job!", "glücklich"),
    ("Ich bin niedergeschlagen, wenn ich an meine Fehler denke.", "traurig"),
    ("Ich bin wütend, wenn meine Pläne durchkreuzt werden.", "wütend"),
    ("Ich habe keine Meinung zu diesem Thema.", "neutral"),
    ("Ich bin glücklich, weil ich meine Ziele erreicht habe!", "glücklich"),
    ("Ich fühle mich melancholisch bei trauriger Musik.", "traurig"),
    ("Ich bin genervt von unfreundlichen Menschen.", "wütend"),
    ("Ich bin neutral gegenüber der heutigen Mode.", "neutral"),
    ("Ich bin begeistert von meiner neuen Kamera!", "glücklich"),
    ("Ich bin bedrückt, wenn ich alleine bin.", "traurig"),
    ("Ich bin frustriert, wenn ich im Stau stehe.", "wütend"),
    ("Ich bin unbeteiligt an dieser Entscheidung.", "neutral"),
    ("Ich bin voller Freude, dass ich endlich Urlaub habe!", "glücklich"),
    ("Ich bin traurig über das Ende einer schönen Zeit.", "traurig"),
    ("Ich bin ärgerlich über die langen Wartezeiten.", "wütend"),
    ("Ich bin gleichgültig gegenüber der neuesten Technik.", "neutral"),








]

import torch
from torch.utils.data import Dataset, DataLoader
from transformers import BertTokenizer, BertForSequenceClassification
from sklearn.model_selection import train_test_split
import torch.optim as optim
import torch.nn.functional as F





label_mapping = {
    "wütend": 0,
    "neutral": 1,
    "glücklich": 2,
    "traurig": 3,
    "ängstlich": 4  
}
texts, labels = zip(*data)
labels = [label_mapping[label] for label in labels]


train_texts, val_texts, train_labels, val_labels = train_test_split(
    texts, labels, test_size=0.2, random_state=42
)


tokenizer = BertTokenizer.from_pretrained("bert-base-german-cased")

class SentimentDataset(Dataset):
    def __init__(self, texts, labels, tokenizer, max_length=128):
        self.encodings = tokenizer(list(texts), padding=True, truncation=True, max_length=max_length, return_tensors="pt")
        self.labels = torch.tensor(labels)

    def __len__(self):
        return len(self.labels)

    def __getitem__(self, idx):
        item = {key: val[idx] for key, val in self.encodings.items()}
        item["labels"] = self.labels[idx]
        return item

train_dataset = SentimentDataset(train_texts, train_labels, tokenizer)
val_dataset = SentimentDataset(val_texts, val_labels, tokenizer)

train_loader = DataLoader(train_dataset, batch_size=4, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=4, shuffle=False)


device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = BertForSequenceClassification.from_pretrained("bert-base-german-cased", num_labels=len(label_mapping))
model.to(device)


optimizer = optim.AdamW(model.parameters(), lr=5e-5)
loss_fn = torch.nn.CrossEntropyLoss()


def train(model, train_loader, optimizer, loss_fn, device):
    model.train()
    total_loss = 0
    for batch in train_loader:
        optimizer.zero_grad()
        batch = {k: v.to(device) for k, v in batch.items()}
        outputs = model(**batch)
        loss = outputs.loss
        loss.backward()
        optimizer.step()
        total_loss += loss.item()
    return total_loss / len(train_loader)


def evaluate(model, val_loader, loss_fn, device):
    model.eval()
    total_loss = 0
    correct = 0
    with torch.no_grad():
        for batch in val_loader:
            batch = {k: v.to(device) for k, v in batch.items()}
            outputs = model(**batch)
            loss = outputs.loss
            total_loss += loss.item()
            preds = torch.argmax(outputs.logits, dim=1)
            correct += (preds == batch["labels"]).sum().item()
    accuracy = correct / len(val_loader.dataset)
    return total_loss / len(val_loader), accuracy


epochs = 3
for epoch in range(epochs):
    train_loss = train(model, train_loader, optimizer, loss_fn, device)
    val_loss, val_acc = evaluate(model, val_loader, loss_fn, device)
    print(f"Epoch {epoch+1}: Train Loss: {train_loss:.4f} | Val Loss: {val_loss:.4f} | Val Accuracy: {val_acc:.4f}")


torch.save(model.state_dict(), "bert_german_sentiment.pth")
